
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "snorkysnark", email = "snorkysnark@gmail.com"},
]
dependencies = [
    "polars>=0.18.4",
    "requests>=2.31.0",
    "tqdm>=4.65.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
